---
- name: Add ppa Repository
  become: yes
  become_user: root
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  become: yes
  become_user: root
  apt: update_cache=yes

- name: Install php7
  become: yes
  become_user: root
  apt: pkg=php7.2 state=latest

- name: Install php7-fpm
  become: yes
  become_user: root
  apt: pkg=php7.2-fpm state=latest

- name: Install PHP Packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=latest
  with_items: '{{ php.packages }}'
  when: php.packages is defined

- include: configure.yml
- include: pecl.yml
