name: Static analysis
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  phpstan:
    name: Larastan code analysis [PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        #php: [ '8.0', 8.1 ]
        php: [7.4]
        #dependency-version: [ prefer-lowest, prefer-stable ]
        dependency-version: [ prefer-stable ]

    services: # Service container Mysql
      mysql: # Label used to access the service container
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: hoomdossier_test
        ports:
          #- 33306:3306
          - 3306:3306
        options: >-  # Set health checks to wait until mysql database has started (it takes some seconds to start)
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Verify hoomdossier_test database exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'hoomdossier_test';"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.actions', '.env.testing'); copy('.env.actions', '.env');" # If .env exist, we use that, if otherwise, copy .env.example to .env and use that instead
      - name: Run composer install
        run: composer install --prefer-dist
      - name: Run larastan (PHPStan) - Static code analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

  phpcs:
    name: PHPcs PSR check [PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        #php: [ '8.0', 8.1 ]
        php: [7.4]
        #dependency-version: [ prefer-lowest, prefer-stable ]
        dependency-version: [ prefer-stable ]

    services: # Service container Mysql
      mysql: # Label used to access the service container
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: hoomdossier_test
        ports:
          #- 33306:3306
          - 3306:3306
        options: >-  # Set health checks to wait until mysql database has started (it takes some seconds to start)
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Verify hoomdossier_test database exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'hoomdossier_test';"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.actions', '.env.testing'); copy('.env.actions', '.env');" # If .env exist, we use that, if otherwise, copy .env.example to .env and use that instead
      - name: Run composer install
        run: composer install --prefer-dist

      - name: Run phpcs - PSR2 check
        run: ./vendor/bin/phpcs --standard=PSR2 app
