name: static-analysis
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        #php: [ '8.0', 8.1 ]
        php: [7.4]
        #dependency-version: [ prefer-lowest, prefer-stable ]
        dependency-version: [ prefer-stable ]
    steps:
        # code & setup
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.actions', '.env.testing'); copy('.env.actions', '.env');" # If .env exist, we use that, if otherwise, copy .env.example to .env and use that instead

      - name: Run composer install
        run: composer install --prefer-dist

      - name: Run larastan (PHPStan) - Static code analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run phpcs - PSR2 check
        run: ./vendor/bin/phpcs --standard=PSR2 app
